# SPX Options Data: Download and Processing

This notebook focuses on extracting and consolidating historical SPX (S&P 500 Index) options data for further analysis and strategy development. The raw data is provided in compressed `.7z` archive format and includes detailed information such as option Greeks, implied volatility, and trading volumes. You can download the spx options data of daily frequency from optionsDX [https://www.optionsdx.com/product/spx-option-chain/]

### Key Objectives:
- Automatically extract `.7z` files containing monthly options data
- Read and process `.csv` or `.txt` files into structured DataFrames
- Merge all monthly data into a single dataset for efficient analysis
- Prepare the data for use in volatility modeling, strategy backtesting, or machine learning

By the end of this notebook, you will have a clean, unified dataset with millions of option quote records across multiple expiries and strikes.

In [1]:
# Use this command to install python library 'py7zr'
#!pip install py7zr

## Data Extraction and Merging

This section handles the entire process of decompressing and reading raw options data files.

### Key Steps:
1. **Setup and Dependencies**
   - Import required libraries (`os`, `pandas`, and `py7zr` for `.7z` extraction).
   - Define the file paths for the source `.7z` files and the folder where extracted data will be stored.

2. **File Extraction**
   - Automatically identifies all `.7z` files in the source directory.
   - Uses `py7zr` to extract each archive to the designated folder.

3. **Reading and Aggregating Data**
   - Iterates over all extracted `.txt` and `.csv` files.
   - Reads each file into a DataFrame and appends it to a list.
   - Skips any non-text files and handles exceptions gracefully.
   - Deletes each file after reading to free up disk space (optional cleanup).

4. **Final Merging**
   - All monthly DataFrames are concatenated into a single DataFrame `options_data_raw`.
   - Displays a confirmation message once data loading is complete.

This results in a consolidated dataset covering SPX options across multiple months.

In [2]:
import os
import pandas as pd
import py7zr  # ✅ Using py7zr for .7z extraction

# Define paths
path = r"C:\Users\varun\Downloads\EPAT New Lecture\data\\"
extract_path = r"C:\Users\varun\Downloads\EPAT New Lecture\data\extracted\\"

# Ensure extraction folder exists
if not os.path.exists(extract_path):
    os.makedirs(extract_path)

# Get all .7z files
dir_list = [f for f in os.listdir(path) if f.endswith(".7z")]

# Extract .7z files
for file_name in dir_list:
    zip_path = os.path.join(path, file_name)

    with py7zr.SevenZipFile(zip_path, mode='r') as archive:
        archive.extractall(extract_path)

# Read extracted files into DataFrame
dfs = []

for file in os.listdir(extract_path):
    file_path = os.path.join(extract_path, file)

    try:
        if file.endswith(".txt") or file.endswith(".csv"):  # Reads .txt and .csv files
            print(f"Reading: {file_path}")
            monthly_data = pd.read_csv(file_path, sep=',', engine='python')

            if not monthly_data.empty:
                dfs.append(monthly_data)
        else:
            print(f"Skipping non-text file: {file}")
    except Exception as e:
        print(f"Error reading {file}: {e}")

    os.remove(file_path)  # Optional cleanup

# Merge all DataFrames
if dfs:
    options_data_raw = pd.concat(dfs, ignore_index=True)
    print("Data extraction and merging complete!")
else:
    print("No valid data found.")

Reading: C:\Users\varun\Downloads\EPAT New Lecture\data\extracted\\spx_eod_202301.txt
Reading: C:\Users\varun\Downloads\EPAT New Lecture\data\extracted\\spx_eod_202302.txt
Reading: C:\Users\varun\Downloads\EPAT New Lecture\data\extracted\\spx_eod_202303.txt
Reading: C:\Users\varun\Downloads\EPAT New Lecture\data\extracted\\spx_eod_202304.txt
Reading: C:\Users\varun\Downloads\EPAT New Lecture\data\extracted\\spx_eod_202305.txt
Reading: C:\Users\varun\Downloads\EPAT New Lecture\data\extracted\\spx_eod_202306.txt
Reading: C:\Users\varun\Downloads\EPAT New Lecture\data\extracted\\spx_eod_202307.txt
Reading: C:\Users\varun\Downloads\EPAT New Lecture\data\extracted\\spx_eod_202308.txt
Reading: C:\Users\varun\Downloads\EPAT New Lecture\data\extracted\\spx_eod_202309.txt
Reading: C:\Users\varun\Downloads\EPAT New Lecture\data\extracted\\spx_eod_202310.txt
Reading: C:\Users\varun\Downloads\EPAT New Lecture\data\extracted\\spx_eod_202311.txt
Reading: C:\Users\varun\Downloads\EPAT New Lecture\data\extracted\\spx_eod_202312.txt
Data extraction and merging complete!

In [3]:
options_data_raw

,[QUOTE_UNIXTIME],[QUOTE_READTIME],[QUOTE_DATE],[QUOTE_TIME_HOURS],[UNDERLYING_LAST],[EXPIRE_DATE],[EXPIRE_UNIX],[DTE],[C_DELTA],[C_GAMMA],...,[P_LAST],[P_DELTA],[P_GAMMA],[P_VEGA],[P_THETA],[P_RHO],[P_IV],[P_VOLUME],[STRIKE_DISTANCE],[STRIKE_DISTANCE_PCT]
0,1672866000,2023-01-04 16:00,2023-01-04,16.0,3853.39,2023-01-04,1672866000,0.0,1.0,0.0,...,0.03,0.0,0.0,0.00023,-0.02481,-0.00033,8.175360,7.000000,2853.4,0.740
1,1672866000,2023-01-04 16:00,2023-01-04,16.0,3853.39,2023-01-04,1672866000,0.0,1.0,0.0,...,0.0,0.0,0.0,0.00044,-0.02531,0.0,7.067240,,2653.4,0.689
2,1672866000,2023-01-04 16:00,2023-01-04,16.0,3853.39,2023-01-04,1672866000,0.0,1.0,0.0,...,0.0,-0.00025,0.0,0.00059,-0.02508,-0.00044,6.138930,,2453.4,0.637
3,1672866000,2023-01-04 16:00,2023-01-04,16.0,3853.39,2023-01-04,1672866000,0.0,1.0,0.0,...,0.0,0.0,0.0,0.00114,-0.02538,0.0,5.331250,,2253.4,0.585
4,1672866000,2023-01-04 16:00,2023-01-04,16.0,3853.39,2023-01-04,1672866000,0.0,1.0,0.0,...,0.0,0.0,0.0,0.001,-0.0255,-0.0002,4.616440,,2053.4,0.533
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2009078,1703883600,2023-12-29 16:00,2023-12-29,16.0,4772.17,2029-12-21,1892581200,2184.0,0.29633,0.00012,...,0.0,-1.0,0.0,0.0,0.0,0.0,,,2427.8,0.509
2009079,1703883600,2023-12-29 16:00,2023-12-29,16.0,4772.17,2029-12-21,1892581200,2184.0,0.27129,0.0001,...,0.0,-1.0,0.0,0.0,0.0,0.0,,,2627.8,0.551
2009080,1703883600,2023-12-29 16:00,2023-12-29,16.0,4772.17,2029-12-21,1892581200,2184.0,0.24709,0.00014,...,0.0,-1.0,0.0,0.0,0.0,0.0,,,2827.8,0.593
2009081,1703883600,2023-12-29 16:00,2023-12-29,16.0,4772.17,2029-12-21,1892581200,2184.0,0.22447,0.00015,...,0.0,-1.0,0.0,0.0,0.0,0.0,,,3027.8,0.634
2009082,1703883600,2023-12-29 16:00,2023-12-29,16.0,4772.17,2029-12-21,1892581200,2184.0,0.20224,0.0001,...,0.0,-1.0,0.0,0.0,0.0,0.0,,,3227.8,0.676

In [4]:
options_data_raw.describe()

,[QUOTE_UNIXTIME],[QUOTE_TIME_HOURS],[UNDERLYING_LAST],[EXPIRE_UNIX],[DTE],[STRIKE],[STRIKE_DISTANCE],[STRIKE_DISTANCE_PCT]
count,2.009083e+06,2009083.0,2.009083e+06,2.009083e+06,2.009083e+06,2.009083e+06,2.009083e+06,2.009083e+06
mean,1.688899e+09,16.0,4.296016e+03,1.699787e+09,1.260212e+02,3.962464e+03,6.779533e+02,1.578288e-01
std,9.038635e+06,0.0,2.295852e+02,2.172615e+07,2.283716e+02,1.008334e+03,8.081813e+02,1.880321e-01
min,1.672866e+09,16.0,3.808190e+03,1.672866e+09,0.000000e+00,1.000000e+02,0.000000e+00,0.000000e+00
25%,1.681157e+09,16.0,4.118310e+03,1.687291e+09,1.600000e+01,3.590000e+03,1.523000e+02,3.600000e-02
50%,1.689278e+09,16.0,4.317960e+03,1.696622e+09,4.400000e+01,4.075000e+03,3.765000e+02,8.800000e-02
75%,1.696882e+09,16.0,4.478550e+03,1.705525e+09,1.449600e+02,4.450000e+03,8.728000e+02,2.030000e-01
max,1.703884e+09,16.0,4.783830e+03,1.892581e+09,2.199000e+03,1.200000e+04,8.191800e+03,2.151000e+00

In [5]:
options_data_raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2009083 entries, 0 to 2009082
Data columns (total 33 columns):
 #   Column                  Dtype
---  ------                  -----
 0   [QUOTE_UNIXTIME]        int64
 1    [QUOTE_READTIME]       object
 2    [QUOTE_DATE]           object
 3    [QUOTE_TIME_HOURS]     float64
 4    [UNDERLYING_LAST]      float64
 5    [EXPIRE_DATE]          object
 6    [EXPIRE_UNIX]          int64
 7    [DTE]                  float64
 8    [C_DELTA]              object
 9    [C_GAMMA]              object
 10   [C_VEGA]               object
 11   [C_THETA]              object
 12   [C_RHO]                object
 13   [C_IV]                 object
 14   [C_VOLUME]             object
 15   [C_LAST]               object
 16   [C_SIZE]               object
 17   [C_BID]                object
 18   [C_ASK]                object
 19   [STRIKE]               float64
 20   [P_BID]                object
 21   [P_ASK]                object
 22   [P_SIZE]               object
 23   [P_LAST]               object
 24   [P_DELTA]              object
 25   [P_GAMMA]              object
 26   [P_VEGA]               object
 27   [P_THETA]              object
 28   [P_RHO]                object
 29   [P_IV]                 object
 30   [P_VOLUME]             object
 31   [STRIKE_DISTANCE]      float64
 32   [STRIKE_DISTANCE_PCT]  float64
dtypes: float64(6), int64(2), object(25)
memory usage: 505.8+ MB

## Cleaning Column Names

The raw dataset contains column names enclosed in square brackets, with inconsistent formatting that may make downstream processing inconvenient. This section standardizes the column names for ease of use.

### Steps:
- Remove square brackets (`[]`) surrounding the names.
- Remove single quotes, if present.
- Replace spaces with underscores to ensure compatibility with typical Python usage.
- Remove any leading underscores that may result from previous replacements.
- Convert all column names to lowercase for consistency.

The result is a set of clean, uniform column names that can be referenced easily in analysis or model-building code.

In [6]:
options_data_raw.columns = (
    options_data_raw.columns
    .str.strip("[]")  # Remove square brackets
    .str.replace("'", "", regex=False)  # Remove single quotes
    .str.replace(" ", "_", regex=False)  # Replace spaces with underscores
    .str.replace(r"^\_+", "", regex=True)  # Remove leading underscores
    .str.replace(r"\[", "", regex=True)  # Remove remaining square brackets
    .str.lower()  # Convert to lowercase
)

# Display the cleaned column names
print(options_data_raw.columns)

Index(['quote_unixtime', 'quote_readtime', 'quote_date', 'quote_time_hours',
       'underlying_last', 'expire_date', 'expire_unix', 'dte', 'c_delta',
       'c_gamma', 'c_vega', 'c_theta', 'c_rho', 'c_iv', 'c_volume', 'c_last',
       'c_size', 'c_bid', 'c_ask', 'strike', 'p_bid', 'p_ask', 'p_size',
       'p_last', 'p_delta', 'p_gamma', 'p_vega', 'p_theta', 'p_rho', 'p_iv',
       'p_volume', 'strike_distance', 'strike_distance_pct'],
      dtype='object')

## Stripping Whitespace from String Columns

Some of the string columns in the dataset may contain leading or trailing spaces, which can lead to issues during filtering, grouping, or comparison operations.

This step ensures that all string values are cleaned by applying `strip()` to each cell in the DataFrame that is of type `str`. This helps maintain data consistency and avoids subtle bugs caused by unwanted whitespace.

In [7]:
# Remove leading and trailing spaces from all string columns
options_data_raw = options_data_raw.applymap(lambda x: x.strip()
                                             if isinstance(x, str) else x)

In [8]:
type(options_data_raw.iloc[-1]['c_iv'])

str

The output confirms that the `c_iv` column contains string values instead of numeric types. This is likely due to the presence of missing values or formatting issues during the CSV import.

To perform numerical analysis or modeling, we need to convert such columns to appropriate numeric types (e.g., `float`). This conversion will be addressed in the following steps.

## Converting Columns to Appropriate Data Types

After inspecting the data, several columns containing numeric values (like implied volatility, Greeks, and prices) were stored as strings. Similarly, date columns were also read as strings. This section converts them to proper numeric and datetime types.

### Steps:
1. **Identify Columns**
   - `float_cols`: All columns that start with `c_` or `p_`, excluding `c_size` and `p_size`, are assumed to be numeric (e.g., delta, gamma, vega).
   - `date_cols`: Any column name containing the substring `"date"` is treated as a date column.

2. **Convert Data Types**
   - Each identified numeric column is converted to `float` using `pd.to_numeric()` with `errors='coerce'` to handle invalid values gracefully.
   - Each identified date column is converted to `datetime` using `pd.to_datetime()`.

3. **Set Index**
   - The `quote_date` column, now in datetime format, is used as the DataFrame index for time-series operations and filtering.

This ensures that the dataset is ready for numerical analysis, time-based grouping, and modeling tasks.

In [9]:
# Identify columns based on their naming patterns
float_cols = [col for col in options_data_raw.columns if col.startswith(("c_", "p_")) and col not in ("c_size", "p_size")]
date_cols = [col for col in options_data_raw.columns if "date" in col.lower()]

# Convert numeric columns
for col in float_cols:
    options_data_raw[col] = pd.to_numeric(options_data_raw[col], errors='coerce')

# Convert date columns
for col in date_cols:
    options_data_raw[col] = pd.to_datetime(options_data_raw[col], errors='coerce')

print("Converted numeric columns:", float_cols)
print("Converted date columns:", date_cols)

# Use quote_date as index
options_data_raw.index = pd.to_datetime(options_data_raw.quote_date)

Converted numeric columns: ['c_delta', 'c_gamma', 'c_vega', 'c_theta', 'c_rho', 'c_iv', 'c_volume', 'c_last', 'c_bid', 'c_ask', 'p_bid', 'p_ask', 'p_last', 'p_delta', 'p_gamma', 'p_vega', 'p_theta', 'p_rho', 'p_iv', 'p_volume']
Converted date columns: ['quote_date', 'expire_date']

#### Understanding `c_size` and `p_size` Columns

The `c_size` and `p_size` columns represent the **bid-ask size** for call and put options, respectively. These values indicate the number of contracts available at the bid and ask prices.

##### Format:
The values are stored as strings

In [10]:
options_data_raw.c_size.unique()

array(['7 x 7', '1 x 1', '10 x 10', ..., '128 x 152', '216 x 292',
       '109 x 83'], dtype=object)

## Dropping Unnecessary Columns and Adding Symbol Information

To streamline the dataset and reduce redundancy, we remove a few columns that are no longer needed for analysis.

### Columns Dropped:
- `quote_date`, `quote_unixtime`, `quote_readtime`, `quote_time_hours`: These columns relate to the timestamp of the quote, which is already captured in the DataFrame index.
- `expire_unix`: A Unix timestamp for expiry, which duplicates the information in the `expire_date` column.

These columns are dropped using the `drop()` method.

### Adding Symbol Column:
A new column named `symbol` is inserted to identify the underlying asset (`SPX`) for all option records. This can be useful when merging with data from other instruments or when generalizing the processing pipeline.

In [11]:
# List of column names to be dropped
columns_to_drop = ['quote_date', 'quote_unixtime', 'quote_readtime', 
       'quote_time_hours',
      'expire_unix']
# Use the drop method to remove the specified columns
options_data_raw.drop(columns=columns_to_drop, inplace=True)

# Add a new column 'SYMBOL' and fill all rows with 'SPX'
options_data_raw.insert(1, 'symbol', 'SPX')

In [12]:
options_data_raw

,underlying_last,symbol,expire_date,dte,c_delta,c_gamma,c_vega,c_theta,c_rho,c_iv,...,p_last,p_delta,p_gamma,p_vega,p_theta,p_rho,p_iv,p_volume,strike_distance,strike_distance_pct
quote_date,,,,,,,,,,,,,,,,,,,,,
2023-01-04,3853.39,SPX,2023-01-04,0.0,1.00000,0.00000,0.00000,0.00000,0.00000,NaN,...,0.03,0.00000,0.0,0.00023,-0.02481,-0.00033,8.17536,7.0,2853.4,0.740
2023-01-04,3853.39,SPX,2023-01-04,0.0,1.00000,0.00000,0.00000,0.00000,0.00000,NaN,...,0.00,0.00000,0.0,0.00044,-0.02531,0.00000,7.06724,NaN,2653.4,0.689
2023-01-04,3853.39,SPX,2023-01-04,0.0,1.00000,0.00000,0.00000,0.00000,0.00000,NaN,...,0.00,-0.00025,0.0,0.00059,-0.02508,-0.00044,6.13893,NaN,2453.4,0.637
2023-01-04,3853.39,SPX,2023-01-04,0.0,1.00000,0.00000,0.00000,0.00000,0.00000,NaN,...,0.00,0.00000,0.0,0.00114,-0.02538,0.00000,5.33125,NaN,2253.4,0.585
2023-01-04,3853.39,SPX,2023-01-04,0.0,1.00000,0.00000,0.00000,0.00000,0.00000,NaN,...,0.00,0.00000,0.0,0.00100,-0.02550,-0.00020,4.61644,NaN,2053.4,0.533
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-12-29,4772.17,SPX,2029-12-21,2184.0,0.29633,0.00012,36.63114,-0.19956,65.38557,0.17401,...,0.00,-1.00000,0.0,0.00000,0.00000,0.00000,NaN,NaN,2427.8,0.509
2023-12-29,4772.17,SPX,2029-12-21,2184.0,0.27129,0.00010,35.36834,-0.18921,60.66536,0.17063,...,0.00,-1.00000,0.0,0.00000,0.00000,0.00000,NaN,NaN,2627.8,0.551
2023-12-29,4772.17,SPX,2029-12-21,2184.0,0.24709,0.00014,33.93840,-0.17756,55.97923,0.16688,...,0.00,-1.00000,0.0,0.00000,0.00000,0.00000,NaN,NaN,2827.8,0.593
2023-12-29,4772.17,SPX,2029-12-21,2184.0,0.22447,0.00015,32.37197,-0.16644,51.39303,0.16395,...,0.00,-1.00000,0.0,0.00000,0.00000,0.00000,NaN,NaN,3027.8,0.634
2023-12-29,4772.17,SPX,2029-12-21,2184.0,0.20224,0.00010,30.71374,-0.15519,46.99074,0.16164,...,0.00,-1.00000,0.0,0.00000,0.00000,0.00000,NaN,NaN,3227.8,0.676

## Classifying Expiry Type

To analyze option behavior across different expiry categories, we define a custom function to classify each option's expiry into types such as Weekly, Monthly, LEAPS, etc.

### Function: `get_expiry_type`
This function compares the quote date and expiry date to assign one of several expiry labels based on calendar logic:

#### Classification Logic:
- **LEAPS**: If the time to expiry is 365 days or more.
- **Near Month / Next Month / Far Month**: If the expiry is the third Friday of the current, next, or the month after next.
- **Monthly (Later Month)**: A third-Friday expiry that is not within the first three months.
- **Weekly**: Any Friday expiry that is not the third Friday of a month.
- **End-of-Month**: If the expiry falls on the last trading day of the month.
- **Daily**: All other expiries (non-Friday, short-dated contracts).

The expiry type is computed row-wise using `.apply()`, where the index (`row.name`) provides the quote date, and the column `expire_date` gives the expiry.

This classification is stored in a new column called `expiry_type` and is essential for analyzing the impact of expiry types on option pricing, liquidity, and strategies.

In [13]:
# Function to classify expiry type
def get_expiry_type(quote_date, expiry_date):
    quote_date = pd.to_datetime(quote_date)
    expiry_date = pd.to_datetime(expiry_date)

    # Check time to expiry
    days_to_expiry = (expiry_date - quote_date).days

    if days_to_expiry >= 365:
        return "LEAPS"

    # Check if it's a Friday
    is_friday = expiry_date.weekday() == 4  # 4 means Friday

    # Compute the third Friday of the current, next, and far month
    third_friday_current = (quote_date + pd.offsets.MonthBegin(1) -
                            pd.offsets.Week(2, weekday=4)).date()
    third_friday_next = (quote_date + pd.DateOffset(months=1) +
                         pd.offsets.MonthBegin(1) -
                         pd.offsets.Week(2, weekday=4)).date()
    third_friday_far = (quote_date + pd.DateOffset(months=2) +
                        pd.offsets.MonthBegin(1) -
                        pd.offsets.Week(2, weekday=4)).date()

    # Monthly Expiry Classification
    if is_friday:
        if expiry_date.date() == third_friday_current:
            return "Near Month"
        elif expiry_date.date() == third_friday_next:
            return "Next Month"
        elif expiry_date.date() == third_friday_far:
            return "Far Month"
        else:
            return "Monthly (Later Month)"

    # Weekly Expiry: Any other Friday that is NOT the third Friday
    if is_friday:
        return "Weekly"

    # End of Month Expiry: Last trading day of the month
    last_trading_day = expiry_date + pd.offsets.MonthEnd(0)
    if expiry_date == last_trading_day:
        return "End-of-Month"

    # Default to daily expiry
    return "Daily"


options_data_raw['expire_date'] = pd.to_datetime(
    options_data_raw['expire_date'])

options_data_raw["expiry_type"] = options_data_raw.apply(
    lambda row: get_expiry_type(row.name, row["expire_date"]),
    axis=1)  # row.name represents the index of the DataFrame

In [14]:
options_data_raw

,underlying_last,symbol,expire_date,dte,c_delta,c_gamma,c_vega,c_theta,c_rho,c_iv,...,p_delta,p_gamma,p_vega,p_theta,p_rho,p_iv,p_volume,strike_distance,strike_distance_pct,expiry_type
quote_date,,,,,,,,,,,,,,,,,,,,,
2023-01-04,3853.39,SPX,2023-01-04,0.0,1.00000,0.00000,0.00000,0.00000,0.00000,NaN,...,0.00000,0.0,0.00023,-0.02481,-0.00033,8.17536,7.0,2853.4,0.740,Daily
2023-01-04,3853.39,SPX,2023-01-04,0.0,1.00000,0.00000,0.00000,0.00000,0.00000,NaN,...,0.00000,0.0,0.00044,-0.02531,0.00000,7.06724,NaN,2653.4,0.689,Daily
2023-01-04,3853.39,SPX,2023-01-04,0.0,1.00000,0.00000,0.00000,0.00000,0.00000,NaN,...,-0.00025,0.0,0.00059,-0.02508,-0.00044,6.13893,NaN,2453.4,0.637,Daily
2023-01-04,3853.39,SPX,2023-01-04,0.0,1.00000,0.00000,0.00000,0.00000,0.00000,NaN,...,0.00000,0.0,0.00114,-0.02538,0.00000,5.33125,NaN,2253.4,0.585,Daily
2023-01-04,3853.39,SPX,2023-01-04,0.0,1.00000,0.00000,0.00000,0.00000,0.00000,NaN,...,0.00000,0.0,0.00100,-0.02550,-0.00020,4.61644,NaN,2053.4,0.533,Daily
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-12-29,4772.17,SPX,2029-12-21,2184.0,0.29633,0.00012,36.63114,-0.19956,65.38557,0.17401,...,-1.00000,0.0,0.00000,0.00000,0.00000,NaN,NaN,2427.8,0.509,LEAPS
2023-12-29,4772.17,SPX,2029-12-21,2184.0,0.27129,0.00010,35.36834,-0.18921,60.66536,0.17063,...,-1.00000,0.0,0.00000,0.00000,0.00000,NaN,NaN,2627.8,0.551,LEAPS
2023-12-29,4772.17,SPX,2029-12-21,2184.0,0.24709,0.00014,33.93840,-0.17756,55.97923,0.16688,...,-1.00000,0.0,0.00000,0.00000,0.00000,NaN,NaN,2827.8,0.593,LEAPS
2023-12-29,4772.17,SPX,2029-12-21,2184.0,0.22447,0.00015,32.37197,-0.16644,51.39303,0.16395,...,-1.00000,0.0,0.00000,0.00000,0.00000,NaN,NaN,3027.8,0.634,LEAPS
2023-12-29,4772.17,SPX,2029-12-21,2184.0,0.20224,0.00010,30.71374,-0.15519,46.99074,0.16164,...,-1.00000,0.0,0.00000,0.00000,0.00000,NaN,NaN,3227.8,0.676,LEAPS

In [15]:
options_data_raw.expiry_type.unique()

array(['Daily', 'Monthly (Later Month)', 'Near Month', 'End-of-Month',
       'Next Month', 'LEAPS', 'Far Month'], dtype=object)

## Saving and Filtering the Final Datasets

After processing and classifying the options data, we save the full dataset to a CSV file for future use. Additionally, we create two separate filtered datasets:

- **Daily Expiry Data**: Contains all options expiring on non-Friday daily expiries.
- **Near Month Expiry Data**: Represents standard monthly options, typically expiring on the third Friday of the month.

Both filtered datasets are saved as separate CSV files for targeted analysis. Finally, we set `quote_date` as the index of the DataFrame to support time series operations.

In [16]:
# Save the cleaned and processed full dataset to CSV
options_data_raw.to_csv('options_spxdata.csv')

# Reload the dataset (ensures clean session or format check)
options_data_raw = pd.read_csv('options_spxdata.csv')

# Filter records with 'Daily' expiry type
options_data_raw_daily  = options_data_raw[options_data_raw.expiry_type == 'Daily']

# Save the filtered Daily expiry data
options_data_raw_daily.to_csv('daily_spxdata_full.csv')

# Filter records with 'Near Month' expiry type (treated as Monthly)
options_data_raw_monthly  = options_data_raw[options_data_raw.expiry_type == 'Near Month']

# Save the filtered Monthly expiry data
options_data_raw_monthly.to_csv('monthly_spxdata_full.csv')

# Set 'quote_date' as the index for time series analysis
options_data_raw.index = options_data_raw.quote_date

# Reassign filtered monthly data after setting index (for downstream use)
options_data_raw_monthly  = options_data_raw[options_data_raw.expiry_type == 'Near Month']

## Inspecting Options Data for a Specific Date

To understand the structure and richness of the processed dataset, we inspect all SPX options quoted on a specific trading day: **January 4, 2023**.

The selected columns include:
- **Meta Info**: `symbol`, `expire_date`, `dte`, `expiry_type`
- **Call Option Metrics**: Greeks (`c_delta`, `c_gamma`, etc.), implied volatility (`c_iv`), market data (`c_bid`, `c_ask`, `c_last`, `c_volume`, `c_size`)
- **Put Option Metrics**: Similar fields for puts (`p_delta`, `p_iv`, etc.)
- **Strike Metrics**: `strike`, `strike_distance`, `strike_distance_pct`

This view helps verify the consistency and completeness of data on a per-day basis, and is useful for selecting sample inputs for modeling or strategy development.

In [17]:
options_data_raw.loc['2023-01-04'][[ 'symbol', 'expire_date', 'dte',
       'c_delta', 'c_gamma', 'c_vega', 'c_theta', 'c_rho', 'c_iv', 'c_volume',
       'c_last', 'c_size', 'c_bid', 'c_ask', 'strike', 'p_bid', 'p_ask',
       'p_size', 'p_last', 'p_delta', 'p_gamma', 'p_vega', 'p_theta', 'p_rho',
       'p_iv', 'p_volume', 'strike_distance', 'strike_distance_pct',
       'expiry_type']]

,symbol,expire_date,dte,c_delta,c_gamma,c_vega,c_theta,c_rho,c_iv,c_volume,...,p_delta,p_gamma,p_vega,p_theta,p_rho,p_iv,p_volume,strike_distance,strike_distance_pct,expiry_type
quote_date,,,,,,,,,,,,,,,,,,,,,
2023-01-04,SPX,2023-01-04,0.0,1.00000,0.00000,0.00000,0.00000,0.00000,NaN,1.0,...,0.00000,0.0,0.00023,-0.02481,-0.00033,8.17536,7.0,2853.4,0.740,Daily
2023-01-04,SPX,2023-01-04,0.0,1.00000,0.00000,0.00000,0.00000,0.00000,NaN,1.0,...,0.00000,0.0,0.00044,-0.02531,0.00000,7.06724,NaN,2653.4,0.689,Daily
2023-01-04,SPX,2023-01-04,0.0,1.00000,0.00000,0.00000,0.00000,0.00000,NaN,NaN,...,-0.00025,0.0,0.00059,-0.02508,-0.00044,6.13893,NaN,2453.4,0.637,Daily
2023-01-04,SPX,2023-01-04,0.0,1.00000,0.00000,0.00000,0.00000,0.00000,NaN,1.0,...,0.00000,0.0,0.00114,-0.02538,0.00000,5.33125,NaN,2253.4,0.585,Daily
2023-01-04,SPX,2023-01-04,0.0,1.00000,0.00000,0.00000,0.00000,0.00000,NaN,NaN,...,0.00000,0.0,0.00100,-0.02550,-0.00020,4.61644,NaN,2053.4,0.533,Daily
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-01-04,SPX,2027-12-17,1808.0,0.05301,0.00002,9.13213,-0.05543,8.72598,0.17269,1.0,...,-1.00000,0.0,0.00000,0.00000,0.00000,NaN,NaN,4946.6,1.284,LEAPS
2023-01-04,SPX,2027-12-17,1808.0,0.03950,0.00007,7.28376,-0.04336,6.61895,0.17094,10.0,...,-1.00000,0.0,0.00000,0.00000,0.00000,NaN,NaN,5346.6,1.388,LEAPS
2023-01-04,SPX,2027-12-17,1808.0,0.03288,0.00008,6.25757,-0.03781,5.49983,0.17239,NaN,...,-1.00000,0.0,0.00000,0.00000,0.00000,NaN,NaN,5746.6,1.491,LEAPS
2023-01-04,SPX,2027-12-17,1808.0,0.02790,0.00008,5.43427,-0.03246,4.63926,0.17480,1.0,...,-1.00000,0.0,0.00000,0.00000,0.00000,NaN,NaN,6146.6,1.595,LEAPS
2023-01-04,SPX,2027-12-17,1808.0,0.01331,0.00001,2.95223,-0.01860,2.25789,0.18573,1.0,...,-1.00000,0.0,0.00000,0.00000,0.00000,NaN,5.0,8146.6,2.114,LEAPS

In [18]:
options_data_raw.columns

Index(['quote_date', 'underlying_last', 'symbol', 'expire_date', 'dte',
       'c_delta', 'c_gamma', 'c_vega', 'c_theta', 'c_rho', 'c_iv', 'c_volume',
       'c_last', 'c_size', 'c_bid', 'c_ask', 'strike', 'p_bid', 'p_ask',
       'p_size', 'p_last', 'p_delta', 'p_gamma', 'p_vega', 'p_theta', 'p_rho',
       'p_iv', 'p_volume', 'strike_distance', 'strike_distance_pct',
       'expiry_type'],
      dtype='object')

## Data processing

## 1. Filter the contracts with last traded value > 0

An option with a last price of zero isn’t realistic for active contracts. Keeping such data could lead to incorrect calculations, such as implied volatility, spreads, or pricing models.

In [19]:
options_data_raw = options_data_raw[(options_data_raw["c_last"] > 0.0)
                                    & (options_data_raw["p_last"] > 0.0)]
options_data_raw

,quote_date,underlying_last,symbol,expire_date,dte,c_delta,c_gamma,c_vega,c_theta,c_rho,...,p_delta,p_gamma,p_vega,p_theta,p_rho,p_iv,p_volume,strike_distance,strike_distance_pct,expiry_type
quote_date,,,,,,,,,,,,,,,,,,,,,
2023-01-04,2023-01-04,3853.39,SPX,2023-01-04,0.0,1.00000,0.00000,0.00000,0.00000,0.00000,...,0.00000,0.00000,0.00023,-0.02481,-0.00033,8.17536,7.0,2853.4,0.740,Daily
2023-01-04,2023-01-04,3853.39,SPX,2023-01-04,0.0,1.00000,0.00000,0.00000,0.00000,0.00000,...,-0.00080,-0.00003,0.00271,-0.02542,-0.00010,1.28427,314.0,753.4,0.196,Daily
2023-01-04,2023-01-04,3853.39,SPX,2023-01-04,0.0,1.00000,0.00000,0.00000,0.00000,0.00000,...,-0.00088,-0.00004,0.00317,-0.02550,-0.00022,1.08159,30.0,653.4,0.170,Daily
2023-01-04,2023-01-04,3853.39,SPX,2023-01-04,0.0,1.00000,0.00000,0.00000,0.00000,0.00000,...,-0.00082,-0.00002,0.00289,-0.02490,-0.00025,0.98132,1.0,603.4,0.157,Daily
2023-01-04,2023-01-04,3853.39,SPX,2023-01-04,0.0,1.00000,0.00000,0.00000,0.00000,0.00000,...,-0.00057,-0.00003,0.00375,-0.02544,0.00000,0.88328,8.0,553.4,0.144,Daily
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-12-29,2023-12-29,4772.17,SPX,2028-12-15,1813.0,0.01515,-0.00001,4.09814,-0.02140,3.29106,...,-1.00000,0.00000,0.00000,0.00000,0.00000,NaN,0.0,7227.8,1.515,LEAPS
2023-12-29,2023-12-29,4772.17,SPX,2029-12-21,2184.0,0.90700,0.00005,11.61324,-0.07469,26.20164,...,-0.02609,0.00005,6.85673,-0.03329,-8.68378,0.30089,1.0,2972.2,0.623,LEAPS
2023-12-29,2023-12-29,4772.17,SPX,2029-12-21,2184.0,0.69773,0.00006,30.19011,-0.20761,85.71353,...,-0.20537,0.00009,30.05622,-0.07625,-49.60489,0.22200,2.0,772.2,0.162,LEAPS
2023-12-29,2023-12-29,4772.17,SPX,2029-12-21,2184.0,0.58848,0.00008,36.20196,-0.23995,95.09132,...,-0.41479,0.00032,37.26064,-0.05655,-64.97551,0.18005,2.0,227.8,0.048,LEAPS
2023-12-29,2023-12-29,4772.17,SPX,2029-12-21,2184.0,0.51373,0.00016,38.65328,-0.24638,93.49492,...,-0.89490,0.00096,11.09994,-0.00463,-15.87522,0.11893,1.0,827.8,0.173,LEAPS

## 2. Filter the contracts with strike distance <=0.05

Working with fewer, more meaningful strike prices speeds up calculation. As an example, we are using a strike distance of 5%.

In [20]:
# # Filter out options where the strike distance percentage is greater than 5%
# # This helps remove strikes that are too far from the underlying price, focusing on relevant contracts
# options_data_raw = options_data_raw[options_data_raw.strike_distance_pct <= 0.15]

# # Display the filtered options data
# options_data_raw

## 3. Remove illiquid contracts bid or ask = 0 X 0

In [21]:
# Filter out options where the call ("c_size") or put ("p_size") has a size of '0 x 0'
# This removes contracts with no market depth (no available bids or asks), indicating illiquidity
options_data_raw = options_data_raw[(options_data_raw['c_size'] != '0 x 0')
                                    & (options_data_raw['p_size'] != '0 x 0')]

# Display the filtered options data
options_data_raw

,quote_date,underlying_last,symbol,expire_date,dte,c_delta,c_gamma,c_vega,c_theta,c_rho,...,p_delta,p_gamma,p_vega,p_theta,p_rho,p_iv,p_volume,strike_distance,strike_distance_pct,expiry_type
quote_date,,,,,,,,,,,,,,,,,,,,,
2023-01-04,2023-01-04,3853.39,SPX,2023-01-04,0.0,1.00000,0.00000,0.00000,0.00000,0.00000,...,0.00000,0.00000,0.00023,-0.02481,-0.00033,8.17536,7.0,2853.4,0.740,Daily
2023-01-04,2023-01-04,3853.39,SPX,2023-01-04,0.0,1.00000,0.00000,0.00000,0.00000,0.00000,...,-0.00080,-0.00003,0.00271,-0.02542,-0.00010,1.28427,314.0,753.4,0.196,Daily
2023-01-04,2023-01-04,3853.39,SPX,2023-01-04,0.0,1.00000,0.00000,0.00000,0.00000,0.00000,...,-0.00088,-0.00004,0.00317,-0.02550,-0.00022,1.08159,30.0,653.4,0.170,Daily
2023-01-04,2023-01-04,3853.39,SPX,2023-01-04,0.0,1.00000,0.00000,0.00000,0.00000,0.00000,...,-0.00082,-0.00002,0.00289,-0.02490,-0.00025,0.98132,1.0,603.4,0.157,Daily
2023-01-04,2023-01-04,3853.39,SPX,2023-01-04,0.0,1.00000,0.00000,0.00000,0.00000,0.00000,...,-0.00057,-0.00003,0.00375,-0.02544,0.00000,0.88328,8.0,553.4,0.144,Daily
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-12-29,2023-12-29,4772.17,SPX,2028-12-15,1813.0,0.01515,-0.00001,4.09814,-0.02140,3.29106,...,-1.00000,0.00000,0.00000,0.00000,0.00000,NaN,0.0,7227.8,1.515,LEAPS
2023-12-29,2023-12-29,4772.17,SPX,2029-12-21,2184.0,0.90700,0.00005,11.61324,-0.07469,26.20164,...,-0.02609,0.00005,6.85673,-0.03329,-8.68378,0.30089,1.0,2972.2,0.623,LEAPS
2023-12-29,2023-12-29,4772.17,SPX,2029-12-21,2184.0,0.69773,0.00006,30.19011,-0.20761,85.71353,...,-0.20537,0.00009,30.05622,-0.07625,-49.60489,0.22200,2.0,772.2,0.162,LEAPS
2023-12-29,2023-12-29,4772.17,SPX,2029-12-21,2184.0,0.58848,0.00008,36.20196,-0.23995,95.09132,...,-0.41479,0.00032,37.26064,-0.05655,-64.97551,0.18005,2.0,227.8,0.048,LEAPS
2023-12-29,2023-12-29,4772.17,SPX,2029-12-21,2184.0,0.51373,0.00016,38.65328,-0.24638,93.49492,...,-0.89490,0.00096,11.09994,-0.00463,-15.87522,0.11893,1.0,827.8,0.173,LEAPS

## 4. Filter based on IV values

In [22]:
# Remove rows where either the call option's implied volatility ("c_iv") or the put option's implied volatility ("p_iv") is missing (NaN)
# This ensures we only work with options that have valid implied volatility values
options_data_raw = options_data_raw.dropna(subset=["c_iv", "p_iv"])

# Display the filtered options data
options_data_raw

,quote_date,underlying_last,symbol,expire_date,dte,c_delta,c_gamma,c_vega,c_theta,c_rho,...,p_delta,p_gamma,p_vega,p_theta,p_rho,p_iv,p_volume,strike_distance,strike_distance_pct,expiry_type
quote_date,,,,,,,,,,,,,,,,,,,,,
2023-01-04,2023-01-04,3853.39,SPX,2023-01-04,0.0,0.00211,0.00014,2.92769,-0.03449,0.06761,...,-1.00000,0.00000,-26.10045,0.00000,0.00000,0.00257,2638.0,1.6,0.000,Daily
2023-01-04,2023-01-04,3853.39,SPX,2023-01-04,0.0,0.00183,0.00014,2.03693,-0.02576,0.04657,...,-0.97158,0.00000,0.00000,-108.45324,-0.07740,0.00260,3144.0,6.6,0.002,Daily
2023-01-04,2023-01-04,3853.39,SPX,2023-01-04,0.0,0.00217,0.00016,1.41177,-0.02494,0.03242,...,-0.97163,0.00000,0.00000,-108.45209,-0.07700,0.00267,2298.0,11.6,0.003,Daily
2023-01-04,2023-01-04,3853.39,SPX,2023-01-04,0.0,0.00236,0.00010,0.97818,-0.02507,0.02208,...,-1.00000,0.00000,-176.09987,0.00000,0.00000,0.00259,2155.0,16.6,0.004,Daily
2023-01-04,2023-01-04,3853.39,SPX,2023-01-04,0.0,0.00153,0.00010,0.67631,-0.02501,0.01536,...,-1.00000,0.00000,-226.10041,0.00000,0.00000,0.00247,651.0,21.6,0.006,Daily
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-12-29,2023-12-29,4772.17,SPX,2028-12-15,1813.0,0.52223,0.00012,36.06815,-0.27288,84.23397,...,-0.62572,0.00054,29.80007,-0.03667,-48.23236,0.14837,1.0,627.8,0.132,LEAPS
2023-12-29,2023-12-29,4772.17,SPX,2029-12-21,2184.0,0.90700,0.00005,11.61324,-0.07469,26.20164,...,-0.02609,0.00005,6.85673,-0.03329,-8.68378,0.30089,1.0,2972.2,0.623,LEAPS
2023-12-29,2023-12-29,4772.17,SPX,2029-12-21,2184.0,0.69773,0.00006,30.19011,-0.20761,85.71353,...,-0.20537,0.00009,30.05622,-0.07625,-49.60489,0.22200,2.0,772.2,0.162,LEAPS
2023-12-29,2023-12-29,4772.17,SPX,2029-12-21,2184.0,0.58848,0.00008,36.20196,-0.23995,95.09132,...,-0.41479,0.00032,37.26064,-0.05655,-64.97551,0.18005,2.0,227.8,0.048,LEAPS
2023-12-29,2023-12-29,4772.17,SPX,2029-12-21,2184.0,0.51373,0.00016,38.65328,-0.24638,93.49492,...,-0.89490,0.00096,11.09994,-0.00463,-15.87522,0.11893,1.0,827.8,0.173,LEAPS

## 5. Filter based on bid and ask values of calls and puts (remove ones with 0 bids or asks)

In [23]:
# Remove options where either the call or put bid/ask prices are zero
# This ensures that only actively traded options with valid market quotes are kept
options_data_raw = options_data_raw[(options_data_raw.c_bid != 0.0) 
                                    & (options_data_raw.p_bid != 0.0) 
                                    & (options_data_raw.c_ask != 0.0) 
                                    & (options_data_raw.p_ask != 0.0)]

# Display the filtered options data
options_data_raw

,quote_date,underlying_last,symbol,expire_date,dte,c_delta,c_gamma,c_vega,c_theta,c_rho,...,p_delta,p_gamma,p_vega,p_theta,p_rho,p_iv,p_volume,strike_distance,strike_distance_pct,expiry_type
quote_date,,,,,,,,,,,,,,,,,,,,,
2023-01-04,2023-01-04,3853.39,SPX,2023-01-05,1.0,0.94891,0.00052,0.26077,-1.15966,0.05262,...,-0.00325,0.00013,0.02468,-0.07464,-0.00083,0.30146,1.0,213.4,0.055,Daily
2023-01-04,2023-01-04,3853.39,SPX,2023-01-05,1.0,0.94730,0.00059,0.26767,-1.26023,0.05664,...,-0.00361,0.00013,0.02605,-0.07488,-0.00038,0.28810,2084.0,203.4,0.053,Daily
2023-01-04,2023-01-04,3853.39,SPX,2023-01-05,1.0,0.94620,0.00070,0.27153,-1.25966,0.05946,...,-0.00387,0.00017,0.02811,-0.07474,-0.00070,0.26831,20.0,188.4,0.049,Daily
2023-01-04,2023-01-04,3853.39,SPX,2023-01-05,1.0,0.92149,0.00241,0.38253,-1.56025,0.08911,...,-0.02479,0.00134,0.15614,-0.41570,-0.00486,0.16952,965.0,88.4,0.023,Daily
2023-01-04,2023-01-04,3853.39,SPX,2023-01-05,1.0,0.94186,0.00440,0.29954,-0.46034,0.06840,...,-0.10746,0.00433,0.49274,-1.92152,-0.01993,0.16010,2252.0,53.4,0.014,Daily
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-12-29,2023-12-29,4772.17,SPX,2028-12-15,1813.0,0.52223,0.00012,36.06815,-0.27288,84.23397,...,-0.62572,0.00054,29.80007,-0.03667,-48.23236,0.14837,1.0,627.8,0.132,LEAPS
2023-12-29,2023-12-29,4772.17,SPX,2029-12-21,2184.0,0.90700,0.00005,11.61324,-0.07469,26.20164,...,-0.02609,0.00005,6.85673,-0.03329,-8.68378,0.30089,1.0,2972.2,0.623,LEAPS
2023-12-29,2023-12-29,4772.17,SPX,2029-12-21,2184.0,0.69773,0.00006,30.19011,-0.20761,85.71353,...,-0.20537,0.00009,30.05622,-0.07625,-49.60489,0.22200,2.0,772.2,0.162,LEAPS
2023-12-29,2023-12-29,4772.17,SPX,2029-12-21,2184.0,0.58848,0.00008,36.20196,-0.23995,95.09132,...,-0.41479,0.00032,37.26064,-0.05655,-64.97551,0.18005,2.0,227.8,0.048,LEAPS
2023-12-29,2023-12-29,4772.17,SPX,2029-12-21,2184.0,0.51373,0.00016,38.65328,-0.24638,93.49492,...,-0.89490,0.00096,11.09994,-0.00463,-15.87522,0.11893,1.0,827.8,0.173,LEAPS

## Check info

In [24]:
# Display a concise summary of the options_data_raw
options_data_raw.info()

<class 'pandas.core.frame.DataFrame'>
Index: 783101 entries, 2023-01-04 to 2023-12-29
Data columns (total 31 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   quote_date           783101 non-null  object
 1   underlying_last      783101 non-null  float64
 2   symbol               783101 non-null  object
 3   expire_date          783101 non-null  object
 4   dte                  783101 non-null  float64
 5   c_delta              783101 non-null  float64
 6   c_gamma              783101 non-null  float64
 7   c_vega               783101 non-null  float64
 8   c_theta              783101 non-null  float64
 9   c_rho                783101 non-null  float64
 10  c_iv                 783101 non-null  float64
 11  c_volume             783101 non-null  float64
 12  c_last               783101 non-null  float64
 13  c_size               783101 non-null  object
 14  c_bid                783101 non-null  float64
 15  c_ask                783101 non-null  float64
 16  strike               783101 non-null  float64
 17  p_bid                783101 non-null  float64
 18  p_ask                783101 non-null  float64
 19  p_size               783101 non-null  object
 20  p_last               783101 non-null  float64
 21  p_delta              783101 non-null  float64
 22  p_gamma              783101 non-null  float64
 23  p_vega               783101 non-null  float64
 24  p_theta              783101 non-null  float64
 25  p_rho                783101 non-null  float64
 26  p_iv                 783101 non-null  float64
 27  p_volume             783101 non-null  float64
 28  strike_distance      783101 non-null  float64
 29  strike_distance_pct  783101 non-null  float64
 30  expiry_type          783101 non-null  object
dtypes: float64(25), object(6)
memory usage: 191.2+ MB

## Filtering and Saving Monthly Expiry Options

This step filters the dataset to include only options contracts classified as having **'Near Month'** expiry — typically standard monthly options expiring on the third Friday of the month.

These options are often the most liquid and widely traded, making them ideal for building and testing strategies.

The filtered subset is saved to a separate CSV file named `monthly_spxdata_filtered.csv` for use in downstream analysis.

In [25]:
# Filter the dataset to include only 'Near Month' expiry options
options_data_raw_monthly = options_data_raw[options_data_raw.expiry_type == 'Near Month']

# Save the filtered monthly data to a CSV file for further analysis or modeling
options_data_raw_monthly.to_csv('monthly_spxdata_filtered.csv')

In [26]:
options_data_raw

,quote_date,underlying_last,symbol,expire_date,dte,c_delta,c_gamma,c_vega,c_theta,c_rho,...,p_delta,p_gamma,p_vega,p_theta,p_rho,p_iv,p_volume,strike_distance,strike_distance_pct,expiry_type
quote_date,,,,,,,,,,,,,,,,,,,,,
2023-01-04,2023-01-04,3853.39,SPX,2023-01-05,1.0,0.94891,0.00052,0.26077,-1.15966,0.05262,...,-0.00325,0.00013,0.02468,-0.07464,-0.00083,0.30146,1.0,213.4,0.055,Daily
2023-01-04,2023-01-04,3853.39,SPX,2023-01-05,1.0,0.94730,0.00059,0.26767,-1.26023,0.05664,...,-0.00361,0.00013,0.02605,-0.07488,-0.00038,0.28810,2084.0,203.4,0.053,Daily
2023-01-04,2023-01-04,3853.39,SPX,2023-01-05,1.0,0.94620,0.00070,0.27153,-1.25966,0.05946,...,-0.00387,0.00017,0.02811,-0.07474,-0.00070,0.26831,20.0,188.4,0.049,Daily
2023-01-04,2023-01-04,3853.39,SPX,2023-01-05,1.0,0.92149,0.00241,0.38253,-1.56025,0.08911,...,-0.02479,0.00134,0.15614,-0.41570,-0.00486,0.16952,965.0,88.4,0.023,Daily
2023-01-04,2023-01-04,3853.39,SPX,2023-01-05,1.0,0.94186,0.00440,0.29954,-0.46034,0.06840,...,-0.10746,0.00433,0.49274,-1.92152,-0.01993,0.16010,2252.0,53.4,0.014,Daily
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-12-29,2023-12-29,4772.17,SPX,2028-12-15,1813.0,0.52223,0.00012,36.06815,-0.27288,84.23397,...,-0.62572,0.00054,29.80007,-0.03667,-48.23236,0.14837,1.0,627.8,0.132,LEAPS
2023-12-29,2023-12-29,4772.17,SPX,2029-12-21,2184.0,0.90700,0.00005,11.61324,-0.07469,26.20164,...,-0.02609,0.00005,6.85673,-0.03329,-8.68378,0.30089,1.0,2972.2,0.623,LEAPS
2023-12-29,2023-12-29,4772.17,SPX,2029-12-21,2184.0,0.69773,0.00006,30.19011,-0.20761,85.71353,...,-0.20537,0.00009,30.05622,-0.07625,-49.60489,0.22200,2.0,772.2,0.162,LEAPS
2023-12-29,2023-12-29,4772.17,SPX,2029-12-21,2184.0,0.58848,0.00008,36.20196,-0.23995,95.09132,...,-0.41479,0.00032,37.26064,-0.05655,-64.97551,0.18005,2.0,227.8,0.048,LEAPS
2023-12-29,2023-12-29,4772.17,SPX,2029-12-21,2184.0,0.51373,0.00016,38.65328,-0.24638,93.49492,...,-0.89490,0.00096,11.09994,-0.00463,-15.87522,0.11893,1.0,827.8,0.173,LEAPS

## Conclusion

In this notebook, we successfully processed and prepared a large dataset of SPX options by performing the following steps:

- Extracted raw options data from compressed `.7z` files.
- Merged multiple monthly files into a single unified DataFrame.
- Cleaned and standardized column names and string values.
- Converted key columns to appropriate numeric and datetime formats.
- Classified each option by expiry type (e.g., Daily, Weekly, Near Month, LEAPS).
- Filtered and exported relevant subsets of the data (e.g., Daily and Monthly expiries).

The resulting dataset is now ready for detailed exploratory analysis, volatility modeling, or options strategy development. With millions of option records enriched with Greeks, pricing data, and structural tags, this forms a strong foundation for building robust, data-driven options trading models.